version: '3'
services:
  ledger_service:
    build:
      context: .
      dockerfile: Dockerfile

  test-postgres:
    image: library/postgres:16-alpine
    restart: unless-stopped
    ports:
    - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledger
    volumes:
    - ./database:/data
